version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234        # root 계정 비밀번호
      MYSQL_DATABASE: project          # 사용할 데이터베이스 이름
      MYSQL_USER: user                # 앱에서 사용할 계정
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/project?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      TOSS_SECRET_KEY: test_sk_
    ports:
      - "8080:8080"

volumes:
  db-data:
