spring:
  application:
    name: project
  datasource:
    url: jdbc:h2:tcp://localhost/~/project
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug

toss:
  secret-key: "test_"